<a href="https://colab.research.google.com/github/psk264/my-notebooks/blob/main/subdir/%22Groceries%22_Exercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Prerequisites

  + [Lists](https://github.com/prof-rossetti/intro-to-python/blob/master/notes/python/datatypes/lists.md)
  + [Dictionaries](https://github.com/prof-rossetti/intro-to-python/blob/master/notes/python/datatypes/dictionaries.md)
  + [List Comprehensions](https://docs.python.org/3/tutorial/datastructures.html?#list-comprehensions)

# Instructions

Make a copy of this notebook so you can edit and save your own version of it. Do the work in your copy of the notebook. 

The setup cell provides a Python variable called `products` and a function called `to_usd`.

Write Python code in the cells below to transform the provided `products` variable into the desired information outputs.

# Setup

In [1]:
#
# SETUP CELL
#

def to_usd(my_price):
    """
    Converts a numeric value to usd-formatted string, for printing and display purposes.
    
    Param: my_price (int or float) like 4000.444444
    
    Example: to_usd(4000.444444)
    
    Returns: $4,000.44
    """
    return f"${my_price:,.2f}" #> $12,000.71

products = [
    {"id":1, "name": "Chocolate Sandwich Cookies", "department": "snacks", "aisle": "cookies cakes", "price": 3.50},
    {"id":2, "name": "All-Seasons Salt", "department": "pantry", "aisle": "spices seasonings", "price": 4.99},
    {"id":3, "name": "Robust Golden Unsweetened Oolong Tea", "department": "beverages", "aisle": "tea", "price": 2.49},
    {"id":4, "name": "Smart Ones Classic Favorites Mini Rigatoni With Vodka Cream Sauce", "department": "frozen", "aisle": "frozen meals", "price": 6.99},
    {"id":5, "name": "Green Chile Anytime Sauce", "department": "pantry", "aisle": "marinades meat preparation", "price": 7.99},
    {"id":6, "name": "Dry Nose Oil", "department": "personal care", "aisle": "cold flu allergy", "price": 21.99},
    {"id":7, "name": "Pure Coconut Water With Orange", "department": "beverages", "aisle": "juice nectars", "price": 3.50},
    {"id":8, "name": "Cut Russet Potatoes Steam N' Mash", "department": "frozen", "aisle": "frozen produce", "price": 4.25},
    {"id":9, "name": "Light Strawberry Blueberry Yogurt", "department": "dairy eggs", "aisle": "yogurt", "price": 6.50},
    {"id":10, "name": "Sparkling Orange Juice & Prickly Pear Beverage", "department": "beverages", "aisle": "water seltzer sparkling water", "price": 2.99},
    {"id":11, "name": "Peach Mango Juice", "department": "beverages", "aisle": "refrigerated", "price": 1.99},
    {"id":12, "name": "Chocolate Fudge Layer Cake", "department": "frozen", "aisle": "frozen dessert", "price": 18.50},
    {"id":13, "name": "Saline Nasal Mist", "department": "personal care", "aisle": "cold flu allergy", "price": 16.00},
    {"id":14, "name": "Fresh Scent Dishwasher Cleaner", "department": "household", "aisle": "dish detergents", "price": 4.99},
    {"id":15, "name": "Overnight Diapers Size 6", "department": "babies", "aisle": "diapers wipes", "price": 25.50},
    {"id":16, "name": "Mint Chocolate Flavored Syrup", "department": "snacks", "aisle": "ice cream toppings", "price": 4.50},
    {"id":17, "name": "Rendered Duck Fat", "department": "meat seafood", "aisle": "poultry counter", "price": 9.99},
    {"id":18, "name": "Pizza for One Suprema Frozen Pizza", "department": "frozen", "aisle": "frozen pizza", "price": 12.50},
    {"id":19, "name": "Gluten Free Quinoa Three Cheese & Mushroom Blend", "department": "dry goods pasta", "aisle": "grains rice dried goods", "price": 3.99},
    {"id":20, "name": "Pomegranate Cranberry & Aloe Vera Enrich Drink", "department": "beverages", "aisle": "juice nectars", "price": 4.25}
] # based on data from Instacart: https://www.instacart.com/datasets/grocery-shopping-2017


In [2]:
# testing the setup process:
print(products)
print(to_usd(12345.6789))

[{'id': 1, 'name': 'Chocolate Sandwich Cookies', 'department': 'snacks', 'aisle': 'cookies cakes', 'price': 3.5}, {'id': 2, 'name': 'All-Seasons Salt', 'department': 'pantry', 'aisle': 'spices seasonings', 'price': 4.99}, {'id': 3, 'name': 'Robust Golden Unsweetened Oolong Tea', 'department': 'beverages', 'aisle': 'tea', 'price': 2.49}, {'id': 4, 'name': 'Smart Ones Classic Favorites Mini Rigatoni With Vodka Cream Sauce', 'department': 'frozen', 'aisle': 'frozen meals', 'price': 6.99}, {'id': 5, 'name': 'Green Chile Anytime Sauce', 'department': 'pantry', 'aisle': 'marinades meat preparation', 'price': 7.99}, {'id': 6, 'name': 'Dry Nose Oil', 'department': 'personal care', 'aisle': 'cold flu allergy', 'price': 21.99}, {'id': 7, 'name': 'Pure Coconut Water With Orange', 'department': 'beverages', 'aisle': 'juice nectars', 'price': 3.5}, {'id': 8, 'name': "Cut Russet Potatoes Steam N' Mash", 'department': 'frozen', 'aisle': 'frozen produce', 'price': 4.25}, {'id': 9, 'name': 'Light Straw

In [35]:
# 
# Part 1 Code
#
# from pprint import pprint
# pprint(products)

import operator

#What type of data is the product variable?
# print("PRODUCTS:",type(products))

# #First item of the list, but what is each itme in the list?
# print("FIRST PRODUCT:", type(products[0]))
# print(products[0])

# #Access key-value of each product
# print("FIRST PRODUCT NAME:", products[0]["name"])
# print("FIRST PRODUCT PRICE:", products[0]["price"])

# #We can ask what are the keys in a dictionary using following method
# print(products[0].keys())

# #We can ask what are the values in a dictionary using following method
# print(products[0].values())

#sorting
products_sorted = sorted(products, key=operator.itemgetter('name'))


#string concat interpolation/print statement with commas
#pass the price to_usd() function
product_counts = len(products)

print("-----------------------")
#print("THERE ARE", len(products), "PRODUCTS:")
print(f"THERE ARE {product_counts} PRODUCTS:")
print("-----------------------")

#looping
for item in products_sorted: 
   print("+", item["name"], "("+ to_usd(item["price"])+")")

-----------------------
THERE ARE 20 PRODUCTS:
-----------------------
+ All-Seasons Salt ($4.99)
+ Chocolate Fudge Layer Cake ($18.50)
+ Chocolate Sandwich Cookies ($3.50)
+ Cut Russet Potatoes Steam N' Mash ($4.25)
+ Dry Nose Oil ($21.99)
+ Fresh Scent Dishwasher Cleaner ($4.99)
+ Gluten Free Quinoa Three Cheese & Mushroom Blend ($3.99)
+ Green Chile Anytime Sauce ($7.99)
+ Light Strawberry Blueberry Yogurt ($6.50)
+ Mint Chocolate Flavored Syrup ($4.50)
+ Overnight Diapers Size 6 ($25.50)
+ Peach Mango Juice ($1.99)
+ Pizza for One Suprema Frozen Pizza ($12.50)
+ Pomegranate Cranberry & Aloe Vera Enrich Drink ($4.25)
+ Pure Coconut Water With Orange ($3.50)
+ Rendered Duck Fat ($9.99)
+ Robust Golden Unsweetened Oolong Tea ($2.49)
+ Saline Nasal Mist ($16.00)
+ Smart Ones Classic Favorites Mini Rigatoni With Vodka Cream Sauce ($6.99)
+ Sparkling Orange Juice & Prickly Pear Beverage ($2.99)


# Part 1

Write python code which references the `products` variable to reproduce the following output, representing a human-friendly list of products:

```
--------------
THERE ARE 20 PRODUCTS:
--------------
 + All-Seasons Salt ($4.99)
 + Chocolate Fudge Layer Cake ($18.50)
 + Chocolate Sandwich Cookies ($3.50)
 + Cut Russet Potatoes Steam N' Mash ($4.25)
 + Dry Nose Oil ($21.99)
 + Fresh Scent Dishwasher Cleaner ($4.99)
 + Gluten Free Quinoa Three Cheese & Mushroom Blend ($3.99)
 + Green Chile Anytime Sauce ($7.99)
 + Light Strawberry Blueberry Yogurt ($6.50)
 + Mint Chocolate Flavored Syrup ($4.50)
 + Overnight Diapers Size 6 ($25.50)
 + Peach Mango Juice ($1.99)
 + Pizza For One Suprema Frozen Pizza ($12.50)
 + Pomegranate Cranberry & Aloe Vera Enrich Drink ($4.25)
 + Pure Coconut Water With Orange ($3.50)
 + Rendered Duck Fat ($9.99)
 + Robust Golden Unsweetened Oolong Tea ($2.49)
 + Saline Nasal Mist ($16.00)
 + Smart Ones Classic Favorites Mini Rigatoni With Vodka Cream Sauce ($6.99)
 + Sparkling Orange Juice & Prickly Pear Beverage ($2.99)
 ```


In [ ]:
#
# PART 1 CODE HERE!
#





# Part 2

Write python code which references the `products` variable to reproduce the following output, representing a human-friendly list of departments:





```
--------------
THERE ARE 10 DEPARTMENTS:
--------------
 + Babies (1 product)
 + Beverages (5 products)
 + Dairy Eggs (1 product)
 + Dry Goods Pasta (1 product)
 + Frozen (4 products)
 + Household (1 product)
 + Meat Seafood (1 product)
 + Pantry (2 products)
 + Personal Care (2 products)
 + Snacks (2 products)
 ```

In [58]:
#
# PART 2 CODE HERE!
#

#Make a departments list from products list
#Steps: 
#1. Get a list of unique department names
#1a. get a list of the department names
#1b. remove duplicate
departments = []
  #option 1 - to get unique departments
# for item in products:
  #if(item["department"] not in departments):  
  #  departments.append(item["department"])

  #option 2 - to get unique departments
for item in products:
  departments.append(item["department"])
departments = list(set(departments))

print(departments)




#2. count the number of departments


#3. loop through the departments

#4. Print
department_count = len(departments)
print("------------------------")
print(f"There are {department_count} departments")
print("------------------------")






['meat seafood', 'personal care', 'dry goods pasta', 'dairy eggs', 'frozen', 'beverages', 'snacks', 'pantry', 'babies', 'household']
------------------------
There are 10 departments
------------------------
